sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  alioss:
    bucket-name: p0tt4t0
    access-key-secret: J6bJ7e6rJyr1RWhuh7B1VUIVBhS5ZT
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDPFowpWjBB5naTzFWb
